# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YBsYmaXiY4E1W3hmomw7zRWDHhC3qYcR
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import requests
from bs4 import BeautifulSoup
import re
import json
from collections import Counter
import time

# ─── Configuración de página ───────────────────────────────────────────────────
st.set_page_config(
    page_title="AnalizaPerú | Noticias con PLN",
    page_icon="🗞️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─── CSS personalizado ──────────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;900&family=Source+Sans+3:wght@300;400;600&display=swap');

html, body, [class*="css"] {
    font-family: 'Source Sans 3', sans-serif;
}

.main-title {
    font-family: 'Playfair Display', serif;
    font-size: 3rem;
    font-weight: 900;
    color: #C0392B;
    line-height: 1.1;
    margin-bottom: 0;
}
.main-subtitle {
    font-family: 'Source Sans 3', sans-serif;
    font-size: 1.1rem;
    color: #7f8c8d;
    font-weight: 300;
    margin-top: 0.2rem;
    margin-bottom: 2rem;
    letter-spacing: 0.08em;
    text-transform: uppercase;
}

.metric-card {
    background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
    border-radius: 12px;
    padding: 1.2rem 1.4rem;
    color: white;
    border-left: 4px solid #C0392B;
    margin-bottom: 0.5rem;
}
.metric-value {
    font-family: 'Playfair Display', serif;
    font-size: 2.2rem;
    font-weight: 700;
    color: #E74C3C;
}
.metric-label {
    font-size: 0.8rem;
    color: #aaa;
    text-transform: uppercase;
    letter-spacing: 0.1em;
}

.news-card {
    background: white;
    border-radius: 10px;
    padding: 1.2rem 1.4rem;
    margin-bottom: 1rem;
    border-top: 3px solid;
    box-shadow: 0 2px 8px rgba(0,0,0,0.08);
}
.news-title { font-weight: 600; font-size: 1rem; margin-bottom: 0.4rem; }
.news-meta { font-size: 0.78rem; color: #888; }

.tag {
    display: inline-block;
    padding: 2px 10px;
    border-radius: 20px;
    font-size: 0.72rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    margin-right: 4px;
}
.tag-positivo { background:#d5f5e3; color:#1e8449; }
.tag-negativo { background:#fadbd8; color:#c0392b; }
.tag-neutro   { background:#eaecee; color:#555; }

.section-header {
    font-family: 'Playfair Display', serif;
    font-size: 1.5rem;
    color: #1a1a2e;
    border-bottom: 2px solid #C0392B;
    padding-bottom: 0.3rem;
    margin-bottom: 1.2rem;
}

.stButton>button {
    background: #C0392B !important;
    color: white !important;
    border: none !important;
    border-radius: 8px !important;
    font-family: 'Source Sans 3', sans-serif !important;
    font-weight: 600 !important;
    letter-spacing: 0.05em !important;
    padding: 0.6rem 1.6rem !important;
}
.stButton>button:hover { background: #a93226 !important; }

div[data-testid="stSidebar"] {
    background: #1a1a2e;
}
div[data-testid="stSidebar"] * { color: #ecf0f1 !important; }
div[data-testid="stSidebar"] .stSelectbox label { color: #aaa !important; }
</style>
""", unsafe_allow_html=True)

# ═══════════════════════════════════════════════════════════════════════════════
#  MÓDULO 1 — SCRAPING
# ═══════════════════════════════════════════════════════════════════════════════

FUENTES = {
    "RPP Noticias": {
        "urls": [
            "https://rpp.pe/politica/elecciones/",
            "https://rpp.pe/futbol/",
            "https://rpp.pe/economia/",
            "https://rpp.pe/actualidad/",
        ],
        "titulo_selector": "h2.story__title, h1.story__title, .story-item__title",
        "desc_selector":   "p.story__summary, .story-item__summary",
    },
    "Líbero": {
        "urls": [
            "https://libero.pe/futbol-peruano/",
            "https://libero.pe/futbol-internacional/",
        ],
        "titulo_selector": "h2.article__title, .list-article__title, h2",
        "desc_selector":   "p.article__summary, .list-article__summary",
    },
}

NOTICIAS_SEED = [
    {
        "titulo": "Alianza Lima y el demoledor récord que conseguirá si vence a FC Cajamarca por el Apertura",
        "descripcion": "Alianza Lima busca sellar una marca sin precedentes en la Liga 1. Un triunfo en Cajamarca activará un registro estadístico que parecía imposible de alcanzar en el fútbol peruano. El equipo de Pablo Guede llegaría a 42 puntos y un promedio de 2.47, superando registros de 1997 y 2000.",
        "fuente": "Líbero",
        "url": "https://libero.pe/futbol-peruano/alianza-lima/2026/05/24/alianza-lima-demoledor-record-conseguira-vence-fc-cajamarca-apertura-2196648",
        "fecha": "24/05/2026",
    },
    {
        "titulo": "Debate de equipos técnicos entre Fuerza Popular y Juntos por el Perú en segunda vuelta",
        "descripcion": "Los equipos técnicos de Fuerza Popular y Juntos por el Perú debaten este domingo 24 de mayo de cara a la segunda vuelta presidencial del próximo 7 de junio. El JNE organizó el debate en su sede de Jesús María con seis bloques temáticos: Reforma del Estado, Juventud y Deporte, Agricultura y Medio Ambiente, Infraestructura, Economía y Empleo, y Salud.",
        "fuente": "RPP Noticias",
        "url": "https://rpp.pe/politica/elecciones/elecciones-2026-debate-de-equipos-tecnicos-entre-fuerza-popular-y-juntos-por-el-peru-en-segunda-vuelta-live-3401",
        "fecha": "24/05/2026",
    },
    {
        "titulo": "Universitario de Deportes empató con CD Moquegua y pierde opciones en la Liga 1",
        "descripcion": "El entrenador Héctor Cúper mostró su decepción tras el empate inesperado ante Moquegua. El equipo crema necesita resultados urgentes para mantenerse en la pelea por el Torneo Apertura 2026 frente a Alianza Lima que ya es campeón.",
        "fuente": "Líbero",
        "url": "https://libero.pe/futbol-peruano/universitario",
        "fecha": "23/05/2026",
    },
    {
        "titulo": "Pedro Francke presenta propuestas económicas de Juntos por el Perú en debate técnico",
        "descripcion": "El exministro de Economía Pedro Francke expuso las propuestas económicas del partido de Roberto Sánchez. Planteó incrementar la inversión pública, reformar el sistema tributario y ampliar programas sociales. Ismael Benavides de Fuerza Popular calificó las propuestas como anticuadas y modelos fracasados.",
        "fuente": "RPP Noticias",
        "url": "https://rpp.pe/politica/elecciones/",
        "fecha": "24/05/2026",
    },
    {
        "titulo": "Sporting Cristal vs ADT: partido clave por el Torneo Apertura Liga 1 2026",
        "descripcion": "Sporting Cristal enfrenta a ADT en partido crucial del Torneo Apertura. El equipo celeste necesita ganar para mantener opciones y no perder más terreno en la tabla de posiciones. Zé Ricardo confía en la recuperación del equipo rimense.",
        "fuente": "Líbero",
        "url": "https://libero.pe/futbol-peruano/sporting-cristal",
        "fecha": "23/05/2026",
    },
    {
        "titulo": "Keiko Fujimori y Roberto Sánchez: segunda vuelta presidencial el 7 de junio",
        "descripcion": "Fuerza Popular y Juntos por el Perú se preparan para la segunda vuelta presidencial. Los candidatos Keiko Fujimori y Roberto Sánchez buscan captar el voto de los electores indecisos. El próximo debate presidencial se realizará el 31 de mayo en la sede del JNE.",
        "fuente": "RPP Noticias",
        "url": "https://rpp.pe/politica/elecciones/",
        "fecha": "24/05/2026",
    },
    {
        "titulo": "Senamhi activa alerta por lluvias extremas en 65 provincias del Perú",
        "descripcion": "El Servicio Nacional de Meteorología e Hidrología del Perú (Senamhi) emitió alertas por precipitaciones intensas en la sierra y selva. Las regiones más afectadas incluyen Cusco, Puno, Huancavelica y Ayacucho. Se recomienda a la población extremar precauciones y evitar zonas de riesgo.",
        "fuente": "RPP Noticias",
        "url": "https://rpp.pe/actualidad/",
        "fecha": "24/05/2026",
    },
    {
        "titulo": "Liga 1: tabla de posiciones tras la fecha 16 del Torneo Apertura 2026",
        "descripcion": "Alianza Lima lidera la tabla con 39 puntos tras la fecha 16 del Apertura. Los blanquiazules ya aseguraron el título del torneo con dos fechas de anticipación bajo la dirección de Pablo Guede. Universitario y Sporting Cristal pelean por los puestos de clasificación internacional.",
        "fuente": "Líbero",
        "url": "https://libero.pe/futbol-peruano/liga-1",
        "fecha": "22/05/2026",
    },
    {
        "titulo": "Dólar en Perú hoy: tipo de cambio sube ante incertidumbre electoral por segunda vuelta",
        "descripcion": "El tipo de cambio del dólar frente al sol peruano registró un incremento ante la incertidumbre generada por el proceso electoral de segunda vuelta. Los mercados financieros peruanos muestran cautela y los analistas advierten posible volatilidad hasta las elecciones del 7 de junio.",
        "fuente": "RPP Noticias",
        "url": "https://rpp.pe/economia/",
        "fecha": "24/05/2026",
    },
    {
        "titulo": "Pablo Guede habló sobre el futuro de Federico Girotti en Alianza Lima",
        "descripcion": "El técnico argentino Pablo Guede se refirió al futuro del delantero Federico Girotti, figura del Torneo Apertura. Guede elogió el rendimiento del atacante y señaló que el club hará lo posible para retenerlo de cara al Torneo Clausura 2026.",
        "fuente": "Líbero",
        "url": "https://libero.pe/futbol-peruano/alianza-lima",
        "fecha": "24/05/2026",
    },
    {
        "titulo": "Congreso del Perú debate proyecto de ley sobre seguridad ciudadana ante ola de criminalidad",
        "descripcion": "El Congreso discute nuevas medidas legislativas para combatir la inseguridad que azota al país. Los legisladores proponen endurecer penas para extorsión y sicariato. La PNP reportó un incremento del 15% en delitos violentos en Lima Metropolitana durante el primer semestre de 2026.",
        "fuente": "RPP Noticias",
        "url": "https://rpp.pe/politica/congreso/",
        "fecha": "23/05/2026",
    },
    {
        "titulo": "Ignacio Buse avanza en Roland Garros y podría enfrentar a Rublev en cuartos",
        "descripcion": "El tenista peruano Ignacio Buse sigue sorprendiendo en Roland Garros con actuaciones sobresalientes. El joven deportista peruano derrotó a su rival en tres sets y podría enfrentarse al ruso Andrey Rublev en la siguiente ronda del Grand Slam francés.",
        "fuente": "Líbero",
        "url": "https://libero.pe/deportes/tenis",
        "fecha": "23/05/2026",
    },
]

@st.cache_data(ttl=1800, show_spinner=False)
def cargar_noticias_adicionales():
    """Intenta scrapear más noticias de RPP. Si falla, retorna lista vacía."""
    extra = []
    headers = {"User-Agent": "Mozilla/5.0 (compatible; AnalizaPeruBot/1.0)"}
    try:
        r = requests.get("https://rpp.pe/ultimas-noticias", headers=headers, timeout=8)
        soup = BeautifulSoup(r.text, "html.parser")
        items = soup.select(".story-item__title")[:8]
        for it in items:
            texto = it.get_text(strip=True)
            if len(texto) > 20:
                extra.append({
                    "titulo": texto,
                    "descripcion": texto,
                    "fuente": "RPP Noticias",
                    "url": "https://rpp.pe",
                    "fecha": "24/05/2026",
                })
    except Exception:
        pass
    return extra

# ═══════════════════════════════════════════════════════════════════════════════
#  MÓDULO 2 — PREPROCESAMIENTO
# ═══════════════════════════════════════════════════════════════════════════════

STOPWORDS_ES = {
    "el","la","los","las","un","una","unos","unas","de","del","al","a","ante",
    "bajo","con","contra","desde","en","entre","hacia","hasta","para","por",
    "según","sin","sobre","tras","y","e","o","u","ni","que","se","su","sus",
    "le","les","lo","me","mi","mis","nos","nuestro","nuestra","ya","fue",
    "son","han","más","pero","si","no","es","como","este","esta","estos",
    "estas","ese","esa","esos","esas","aquel","aquella","yo","tú","él","ella",
    "también","así","muy","bien","cuando","donde","quien","cual","cuál","qué",
    "cómo","cuándo","dónde","después","antes","durante","mientras","aunque",
    "porque","si","sino","pues","luego","entonces","además","incluso","solo",
    "solo","con","entre","tras","ante","bajo","hasta","según","sin","sobre",
    "ha","ser","estar","haber","tener","hacer","poder","ir","ver","dar","saber",
    "querer","llegar","pasar","deber","poner","parecer","quedar","creer","hablar",
    "llevar","dejar","seguir","encontrar","llamar","venir","pensar","salir","volver",
    "tomar","conocer","vivir","sentir","tratar","mirar","contar","empezar","esperar",
    "buscar","existir","entrar","trabajar","escribir","perder","producir","ocurrir",
    "entender","pedir","recibir","recordar","terminar","permitir","aparecer","conseguir",
    "comenzar","servir","sacar","necesitar","mantener","resultar","leer","caer",
    "cambiar","presentar","crear","abrir","considerar","oír","puede","tiene",
}

CATEGORIAS_KEYWORDS = {
    "Política":   ["elecciones","presidente","congreso","gobierno","ley","partido","keiko","sánchez","fujimori","jne","fuerza","popular","debate","voto","candidato","político"],
    "Deportes":   ["alianza","universitario","sporting","cristal","liga","torneo","apertura","clausura","gol","partido","fútbol","deporte","tenis","voley","equipo","campeón","guede","buse","roland"],
    "Economía":   ["dólar","sol","tipo","cambio","economía","inversión","banco","precio","mercado","inflación","empleo","sunat","finanzas","tributario","igv"],
    "Seguridad":  ["crimen","delito","policía","pnp","robo","asesinato","extorsión","sicariato","seguridad","criminal","banda","narcotráfico"],
    "Clima":      ["senamhi","lluvia","sismo","temblor","terremoto","fenómeno","alerta","clima","temperatura","huaico","inundación","emergencia"],
    "Internacional": ["mundial","europa","estados","unidos","argentina","chile","colombia","china","rusia","eeuu","internacional","global"],
}

PALABRAS_POSITIVAS = {
    "récord","campeón","triunfo","victoria","logro","éxito","avance","mejora",
    "positivo","ganó","gana","lidera","destaca","crecimiento","progreso","excelente",
    "histórico","demoledor","sorprende","bien","bueno","gran","mejor","importante",
    "alturado","refuerza","aplaude","celebra","avanzó","clasificó","apoya",
}
PALABRAS_NEGATIVAS = {
    "crisis","corrupción","escándalo","derrota","pérdida","caída","fracaso",
    "problema","conflicto","negativo","malo","peor","pésimo","riesgo","peligro",
    "violencia","crimen","delito","alerta","emergencia","caos","incertidumbre",
    "anticuado","fracasado","decepción","protesta","huelga","impunidad","acusado",
    "ola","extorsión","sicariato","criminalidad","lluvia","sismo",
}

def limpiar_texto(texto: str) -> str:
    texto = texto.lower()
    texto = re.sub(r"http\S+|www\S+", "", texto)
    texto = re.sub(r"[^\w\sáéíóúüñ]", " ", texto)
    texto = re.sub(r"\d+", "", texto)
    texto = re.sub(r"\s+", " ", texto).strip()
    return texto

def tokenizar(texto: str) -> list:
    return [t for t in texto.split() if len(t) > 2]

def eliminar_stopwords(tokens: list) -> list:
    return [t for t in tokens if t not in STOPWORDS_ES]

def lematizar_simple(token: str) -> str:
    sufijos = [("aciones","ación"),("iendo","er"),("ando","ar"),
               ("aron","ar"),("aron","ar"),("ados","ado"),("adas","ada"),
               ("mente",""),("ísimo","o"),("ísima","a")]
    for suf, rep in sufijos:
        if token.endswith(suf) and len(token) > len(suf) + 3:
            return token[:-len(suf)] + rep
    return token

def preprocesar(texto: str) -> dict:
    limpio    = limpiar_texto(texto)
    tokens    = tokenizar(limpio)
    sin_stop  = eliminar_stopwords(tokens)
    lematizados = [lematizar_simple(t) for t in sin_stop]
    return {
        "texto_limpio": limpio,
        "tokens":       tokens,
        "tokens_sin_stopwords": sin_stop,
        "lemas":        lematizados,
        "n_tokens":     len(tokens),
        "n_palabras_utiles": len(sin_stop),
    }

# ═══════════════════════════════════════════════════════════════════════════════
#  MÓDULO 3 — TÉCNICAS PLN
# ═══════════════════════════════════════════════════════════════════════════════

# ── 3.1 Clasificación de texto ──────────────────────────────────────────────────
def clasificar_categoria(titulo: str, descripcion: str) -> str:
    texto = (titulo + " " + descripcion).lower()
    scores = {}
    for cat, kws in CATEGORIAS_KEYWORDS.items():
        scores[cat] = sum(1 for kw in kws if kw in texto)
    mejor = max(scores, key=scores.get)
    return mejor if scores[mejor] > 0 else "General"

# ── 3.2 Análisis de sentimiento ─────────────────────────────────────────────────
def analizar_sentimiento(titulo: str, descripcion: str) -> dict:
    texto = (titulo + " " + descripcion).lower()
    tokens = re.findall(r"\b\w+\b", texto)
    pos = sum(1 for t in tokens if t in PALABRAS_POSITIVAS)
    neg = sum(1 for t in tokens if t in PALABRAS_NEGATIVAS)
    total = pos + neg
    if total == 0:
        return {"etiqueta": "Neutro", "score": 0.0, "positivas": 0, "negativas": 0}
    score = (pos - neg) / total
    if score > 0.15:
        etiqueta = "Positivo"
    elif score < -0.15:
        etiqueta = "Negativo"
    else:
        etiqueta = "Neutro"
    return {"etiqueta": etiqueta, "score": round(score, 3),
            "positivas": pos, "negativas": neg}

# ── 3.3 Reconocimiento de entidades (NER) ──────────────────────────────────────
PERSONAS = {
    "pablo guede","keiko fujimori","roberto sánchez","pedro francke",
    "ismael benavides","hernando cevallos","federico girotti","paolo guerrero",
    "hector cupe","héctor cúper","ze ricardo","zé ricardo",
    "ignacio buse","andrey rublev","sinesio lópez","rosangella barbarán",
    "carlos neuhaus","gustavo guerra","luis carranza","fatima chavez",
    "fátima chávez","wilfredo inostroza","jorge fossati",
}
ORGANIZACIONES = {
    "alianza lima","universitario","sporting cristal","fc cajamarca",
    "fuerza popular","juntos por el perú","jne","jurado nacional de elecciones",
    "pnp","policía nacional","senamhi","sunat","onpe","congreso",
    "liga 1","liga 1 te apuesto","rpp","libero","andina",
    "adt","cd moquegua","cienciano","melgar",
}
LUGARES = {
    "lima","perú","cajamarca","cusco","arequipa","piura","trujillo",
    "huancayo","puno","ayacucho","ica","tacna","moquegua","huancavelica",
    "junín","loreto","callao","jesús maría","lurigancho","chosica",
    "tarma","francia","europa","buenos aires","argentina",
}

def extraer_entidades(texto: str) -> dict:
    texto_lower = texto.lower()
    entidades = {"PERSONA": [], "ORGANIZACIÓN": [], "LUGAR": []}
    for p in PERSONAS:
        if p in texto_lower:
            entidades["PERSONA"].append(p.title())
    for o in ORGANIZACIONES:
        if o in texto_lower:
            entidades["ORGANIZACIÓN"].append(o.title())
    for l in LUGARES:
        if re.search(r"\b" + l + r"\b", texto_lower):
            entidades["LUGAR"].append(l.title())
    return {k: list(set(v)) for k, v in entidades.items()}

# ── Pipeline completo ────────────────────────────────────────────────────────────
def analizar_noticia(noticia: dict) -> dict:
    titulo  = noticia.get("titulo", "")
    desc    = noticia.get("descripcion", titulo)
    texto_completo = titulo + ". " + desc
    prep = preprocesar(texto_completo)
    cat  = clasificar_categoria(titulo, desc)
    sent = analizar_sentimiento(titulo, desc)
    ner  = extraer_entidades(texto_completo)
    palabras_freq = Counter(prep["tokens_sin_stopwords"]).most_common(6)
    return {**noticia, "categoria": cat, "sentimiento": sent["etiqueta"],
            "score_sentimiento": sent["score"],
            "palabras_pos": sent["positivas"], "palabras_neg": sent["negativas"],
            "entidades": ner,
            "n_entidades": sum(len(v) for v in ner.values()),
            "tokens_utiles": prep["n_palabras_utiles"],
            "palabras_freq": palabras_freq,
            "texto_limpio": prep["texto_limpio"]}

#  CARGA DE DATOS
@st.cache_data(show_spinner=False)
def cargar_y_analizar():
    extras = cargar_noticias_adicionales()
    todas  = NOTICIAS_SEED + extras
    return [analizar_noticia(n) for n in todas]

#  INTERFAZ

# ── Sidebar ─────
with st.sidebar:
    st.markdown("## 🗞️ AnalizaPerú")
    st.markdown("*Análisis de noticias peruanas con PLN*")
    st.divider()

    seccion = st.radio(
        "Sección",
        ["📊 Dashboard", "🔍 Analizar texto", "📰 Noticias", "🧪 Técnicas PLN"],
        label_visibility="collapsed",
    )

    st.divider()
    st.markdown("**Fuentes de datos**")
    st.markdown("- 🔴 RPP Noticias\n- 🔵 Diario Líbero")
    st.divider()
    st.markdown("**Técnicas PLN aplicadas**")
    st.markdown("1. Clasificación de texto\n2. Análisis de sentimiento\n3. NER (entidades)")

# ── Carga ────────
with st.spinner("⏳ Cargando y analizando noticias…"):
    noticias = cargar_y_analizar()

df = pd.DataFrame(noticias)

# ── Paleta por categoría ───────
COLORES_CAT = {
    "Política":"#E74C3C","Deportes":"#2980B9","Economía":"#27AE60",
    "Seguridad":"#8E44AD","Clima":"#F39C12","Internacional":"#16A085","General":"#7F8C8D",
}
COLORES_SENT = {"Positivo":"#27AE60","Negativo":"#E74C3C","Neutro":"#95A5A6"}

#  SECCIÓN: DASHBOARD
if "Dashboard" in seccion:
    st.markdown('<p class="main-title">AnalizaPerú</p>', unsafe_allow_html=True)
    st.markdown('<p class="main-subtitle">Sistema Inteligente de Análisis de Noticias Peruanas · PLN 2026</p>', unsafe_allow_html=True)

    # Métricas
    c1, c2, c3, c4 = st.columns(4)
    with c1:
        st.markdown(f'<div class="metric-card"><div class="metric-value">{len(df)}</div><div class="metric-label">Noticias analizadas</div></div>', unsafe_allow_html=True)
    with c2:
        pct_pos = round(len(df[df.sentimiento=="Positivo"])/len(df)*100)
        st.markdown(f'<div class="metric-card"><div class="metric-value">{pct_pos}%</div><div class="metric-label">Tono positivo</div></div>', unsafe_allow_html=True)
    with c3:
        tot_ent = df.n_entidades.sum()
        st.markdown(f'<div class="metric-card"><div class="metric-value">{tot_ent}</div><div class="metric-label">Entidades detectadas</div></div>', unsafe_allow_html=True)
    with c4:
        n_cats = df.categoria.nunique()
        st.markdown(f'<div class="metric-card"><div class="metric-value">{n_cats}</div><div class="metric-label">Categorías</div></div>', unsafe_allow_html=True)

    st.markdown("---")

    col_a, col_b = st.columns(2)
    with col_a:
        st.markdown('<p class="section-header">Noticias por categoría</p>', unsafe_allow_html=True)
        cat_counts = df.categoria.value_counts().reset_index()
        cat_counts.columns = ["Categoría", "Total"]
        fig_cat = px.bar(cat_counts, x="Total", y="Categoría", orientation="h",
                         color="Categoría", color_discrete_map=COLORES_CAT,
                         template="plotly_white")
        fig_cat.update_layout(showlegend=False, margin=dict(l=0,r=0,t=10,b=0), height=280)
        st.plotly_chart(fig_cat, use_container_width=True)

    with col_b:
        st.markdown('<p class="section-header">Distribución de sentimiento</p>', unsafe_allow_html=True)
        sent_counts = df.sentimiento.value_counts().reset_index()
        sent_counts.columns = ["Sentimiento", "Total"]
        fig_sent = px.pie(sent_counts, values="Total", names="Sentimiento",
                          color="Sentimiento", color_discrete_map=COLORES_SENT,
                          hole=0.5, template="plotly_white")
        fig_sent.update_layout(margin=dict(l=0,r=0,t=10,b=0), height=280)
        st.plotly_chart(fig_sent, use_container_width=True)

    # Tabla de entidades más frecuentes
    st.markdown('<p class="section-header">Entidades más mencionadas</p>', unsafe_allow_html=True)
    all_pers, all_org, all_lug = [], [], []
    for _, row in df.iterrows():
        ent = row.get("entidades", {})
        all_pers.extend(ent.get("PERSONA", []))
        all_org.extend(ent.get("ORGANIZACIÓN", []))
        all_lug.extend(ent.get("LUGAR", []))

    col_e1, col_e2, col_e3 = st.columns(3)
    for col, lista, emoji, titulo in [
        (col_e1, all_pers, "👤", "Personas"),
        (col_e2, all_org, "🏛️", "Organizaciones"),
        (col_e3, all_lug, "📍", "Lugares"),
    ]:
        with col:
            st.markdown(f"**{emoji} {titulo}**")
            cnt = Counter(lista).most_common(5)
            for nombre, n in cnt:
                st.markdown(f"- {nombre} `×{n}`")

    # Scatter sentimiento vs entidades
    st.markdown('<p class="section-header">Sentimiento vs. riqueza de entidades</p>', unsafe_allow_html=True)
    fig_sc = px.scatter(df, x="score_sentimiento", y="n_entidades",
                        color="categoria", size="tokens_utiles",
                        hover_data=["titulo","fuente"],
                        color_discrete_map=COLORES_CAT,
                        labels={"score_sentimiento":"Score sentimiento",
                                "n_entidades":"N° entidades","categoria":"Categoría"},
                        template="plotly_white")
    fig_sc.add_vline(x=0, line_dash="dash", line_color="#aaa")
    fig_sc.update_layout(height=350, margin=dict(l=0,r=0,t=10,b=0))
    st.plotly_chart(fig_sc, use_container_width=True)

#  SECCIÓN: ANALIZAR TEXTO

if "Analizar" in seccion:
    st.markdown('<p class="main-title">AnalizaPerú</p>', unsafe_allow_html=True)
    st.markdown('<p class="main-subtitle">Escribe o pega cualquier noticia peruana para analizarla en tiempo real</p>', unsafe_allow_html=True)

    titulo_in = st.text_input("Título de la noticia", placeholder="Ej: Alianza Lima logra récord histórico en la Liga 1…")
    cuerpo_in = st.text_area("Cuerpo / descripción", height=160,
                              placeholder="Pega aquí el texto de la noticia…")

    if st.button("🔍 Analizar con PLN"):
        if not titulo_in.strip():
            st.warning("Ingresa al menos un título.")
        else:
            noticia_custom = {"titulo": titulo_in, "descripcion": cuerpo_in or titulo_in,
                              "fuente": "Manual", "url": "", "fecha": "Hoy"}
            res = analizar_noticia(noticia_custom)

            st.markdown("---")
            st.markdown("### Resultados del análisis")

            ca, cb, cc = st.columns(3)
            ca.metric("Categoría", res["categoria"])
            cb.metric("Sentimiento", res["sentimiento"])
            cc.metric("Entidades detectadas", res["n_entidades"])

            c1, c2 = st.columns(2)
            with c1:
                st.markdown("**🧹 Preprocesamiento**")
                prep = preprocesar(titulo_in + ". " + (cuerpo_in or ""))
                st.json({
                    "tokens_totales":   prep["n_tokens"],
                    "palabras_útiles":  prep["n_palabras_utiles"],
                    "muestra_lemas":    prep["lemas"][:12]
                })

            with c2:
                st.markdown("**🏷️ Entidades (NER)**")
                ner = res["entidades"]
                for tipo, lista in ner.items():
                    if lista:
                        st.markdown(f"**{tipo}:** {', '.join(lista)}")

            st.markdown("**📊 Palabras más frecuentes (sin stopwords)**")
            if res["palabras_freq"]:
                wdf = pd.DataFrame(res["palabras_freq"], columns=["Palabra","Frecuencia"])
                fig_w = px.bar(wdf, x="Frecuencia", y="Palabra", orientation="h",
                               color_discrete_sequence=["#C0392B"], template="plotly_white")
                fig_w.update_layout(height=220, margin=dict(l=0,r=0,t=5,b=0), showlegend=False)
                st.plotly_chart(fig_w, use_container_width=True)

            # Score de sentimiento visual
            score = res["score_sentimiento"]
            fig_gauge = go.Figure(go.Indicator(
                mode="gauge+number",
                value=round(score * 100),
                title={"text": "Score de sentimiento (−100 → +100)"},
                gauge={
                    "axis":{"range":[-100,100]},
                    "bar":{"color":"#C0392B"},
                    "steps":[
                        {"range":[-100,-15],"color":"#fadbd8"},
                        {"range":[-15,15],"color":"#eaecee"},
                        {"range":[15,100],"color":"#d5f5e3"}
                    ],
                    "threshold":{"line":{"color":"black","width":2},"value":score*100}
                },
            ))
            fig_gauge.update_layout(height=250, margin=dict(l=20,r=20,t=30,b=0))
            st.plotly_chart(fig_gauge, use_container_width=True)

# ════════════════════════════════════════════════════════════════════════════════
#  SECCIÓN: NOTICIAS
# ════════════════════════════════════════════════════════════════════════════════
if "Noticias" in seccion:
    st.markdown('<p class="main-title">Noticias analizadas</p>', unsafe_allow_html=True)
    st.markdown('<p class="main-subtitle">Filtros y detalle de cada noticia procesada</p>', unsafe_allow_html=True)

    col_f1, col_f2, col_f3 = st.columns(3)
    with col_f1:
        cats = ["Todas"] + sorted(df.categoria.unique().tolist())
        filtro_cat = st.selectbox("Categoría", cats)
    with col_f2:
        sents = ["Todos","Positivo","Neutro","Negativo"]
        filtro_sent = st.selectbox("Sentimiento", sents)
    with col_f3:
        fuentes = ["Todas"] + sorted(df.fuente.unique().tolist())
        filtro_fuente = st.selectbox("Fuente", fuentes)

    df_fil = df.copy()
    if filtro_cat   != "Todas":   df_fil = df_fil[df_fil.categoria == filtro_cat]
    if filtro_sent  != "Todos":   df_fil = df_fil[df_fil.sentimiento == filtro_sent]
    if filtro_fuente != "Todas":  df_fil = df_fil[df_fil.fuente == filtro_fuente]

    st.markdown(f"**{len(df_fil)} noticias**")

    for _, row in df_fil.iterrows():
        color_borde = COLORES_CAT.get(row["categoria"], "#ccc")
        tag_class   = {"Positivo":"tag-positivo","Negativo":"tag-negativo","Neutro":"tag-neutro"}.get(row["sentimiento"],"tag-neutro")
        ents_str = ""
        for tipo, lista in row["entidades"].items():
            if lista:
                ents_str += f"<span style='font-size:0.75rem;color:#555'>{tipo}: {', '.join(lista[:3])}</span><br>"
        st.markdown(f"""
        <div class="news-card" style="border-top-color:{color_borde}">
            <div class="news-title">{row['titulo']}</div>
            <div class="news-meta">
                📰 {row['fuente']} &nbsp;·&nbsp; 📅 {row['fecha']} &nbsp;·&nbsp;
                <span class="tag" style="background:{color_borde}22;color:{color_borde}">{row['categoria']}</span>
                <span class="tag {tag_class}">{row['sentimiento']}</span>
            </div>
            <br>{ents_str}
        </div>
        """, unsafe_allow_html=True)

# ════════════════════════════════════════════════════════════════════════════════
#  SECCIÓN: TÉCNICAS PLN
# ════════════════════════════════════════════════════════════════════════════════
if "Técnicas" in seccion:
    st.markdown('<p class="main-title">Técnicas PLN</p>', unsafe_allow_html=True)
    st.markdown('<p class="main-subtitle">Explicación y demostración de cada técnica aplicada</p>', unsafe_allow_html=True)

    tab1, tab2, tab3, tab4 = st.tabs(["🧹 Preprocesamiento", "📂 Clasificación", "😊 Sentimiento", "🏷️ NER"])

    with tab1:
        st.markdown("### Preprocesamiento de texto")
        st.markdown("""
        El preprocesamiento transforma el texto crudo en una representación limpia y estructurada.
        Las etapas aplicadas son:

        1. **Limpieza** — eliminar URLs, números, signos de puntuación
        2. **Tokenización** — dividir el texto en palabras individuales
        3. **Eliminación de stopwords** — quitar palabras sin valor semántico (artículos, preposiciones)
        4. **Lematización** — reducir palabras a su forma base mediante reglas de sufijos
        """)
        ejemplo = st.selectbox("Selecciona una noticia para ver el preprocesamiento:", df.titulo.tolist())
        row_ej = df[df.titulo == ejemplo].iloc[0]
        texto_ej = row_ej["titulo"] + ". " + row_ej.get("descripcion", "")
        prep_ej = preprocesar(texto_ej)

        col_p1, col_p2 = st.columns(2)
        with col_p1:
            st.markdown("**Texto original:**")
            st.info(texto_ej[:300])
            st.markdown("**Texto limpio:**")
            st.success(prep_ej["texto_limpio"][:300])
        with col_p2:
            st.markdown(f"**Tokens ({prep_ej['n_tokens']}):**")
            st.code(" | ".join(prep_ej["tokens"][:20]))
            st.markdown(f"**Sin stopwords ({prep_ej['n_palabras_utiles']}):**")
            st.code(" | ".join(prep_ej["tokens_sin_stopwords"][:20]))
            st.markdown("**Lemas:**")
            st.code(" | ".join(prep_ej["lemas"][:20]))

    with tab2:
        st.markdown("### Clasificación de texto")
        st.markdown("""
        Se aplica un **clasificador basado en diccionario de keywords** por categoría.
        Para cada noticia, se cuenta cuántas palabras clave de cada categoría aparecen
        en el título y la descripción, y se asigna la categoría con mayor score.

        **Categorías disponibles:** Política, Deportes, Economía, Seguridad, Clima, Internacional.
        """)
        # Matriz de confusión visual — distribución por categoría y fuente
        cat_fuente = df.groupby(["categoria","fuente"]).size().reset_index(name="n")
        fig_cf = px.bar(cat_fuente, x="categoria", y="n", color="fuente",
                        barmode="group", template="plotly_white",
                        color_discrete_sequence=["#C0392B","#2980B9"],
                        labels={"categoria":"Categoría","n":"Noticias","fuente":"Fuente"})
        fig_cf.update_layout(height=320, margin=dict(l=0,r=0,t=10,b=0))
        st.plotly_chart(fig_cf, use_container_width=True)

        st.markdown("**Keywords por categoría:**")
        for cat, kws in CATEGORIAS_KEYWORDS.items():
            st.markdown(f"- **{cat}:** {', '.join(kws[:8])}…")

    with tab3:
        st.markdown("### Análisis de sentimiento")
        st.markdown("""
        Se utiliza un **léxico de polaridad** con palabras positivas y negativas en español.
        El score se calcula como: `(positivas − negativas) / total_polarizadas`

        - Score > 0.15 → **Positivo**
        - Score < −0.15 → **Negativo**
        - Entre −0.15 y 0.15 → **Neutro**
        """)
        fig_box = px.box(df, x="sentimiento", y="score_sentimiento",
                         color="sentimiento", color_discrete_map=COLORES_SENT,
                         template="plotly_white",
                         labels={"sentimiento":"Sentimiento","score_sentimiento":"Score"})
        fig_box.update_layout(height=300, margin=dict(l=0,r=0,t=10,b=0), showlegend=False)
        st.plotly_chart(fig_box, use_container_width=True)

        st.markdown("**Distribución por categoría:**")
        sent_cat = df.groupby(["categoria","sentimiento"]).size().reset_index(name="n")
        fig_sc2 = px.bar(sent_cat, x="categoria", y="n", color="sentimiento",
                         barmode="stack", color_discrete_map=COLORES_SENT,
                         template="plotly_white",
                         labels={"categoria":"Categoría","n":"Noticias"})
        fig_sc2.update_layout(height=280, margin=dict(l=0,r=0,t=10,b=0))
        st.plotly_chart(fig_sc2, use_container_width=True)

    with tab4:
        st.markdown("### Reconocimiento de Entidades (NER)")
        st.markdown("""
        El NER identifica y clasifica menciones de **entidades nombradas** en el texto:

        - 👤 **PERSONA** — políticos, deportistas, periodistas
        - 🏛️ **ORGANIZACIÓN** — partidos, clubes, instituciones
        - 📍 **LUGAR** — ciudades, regiones, países

        Se implementa mediante un **gazeteer** (diccionario de entidades conocidas del contexto peruano)
        con búsqueda de subcadenas sobre el texto normalizado.
        """)
        all_ent = []
        for _, row in df.iterrows():
            for tipo, lista in row["entidades"].items():
                for e in lista:
                    all_ent.append({"Entidad": e, "Tipo": tipo, "Categoría noticia": row["categoria"]})
        df_ent = pd.DataFrame(all_ent)
        if not df_ent.empty:
            top_ent = df_ent.Entidad.value_counts().head(12).reset_index()
            top_ent.columns = ["Entidad","Menciones"]
            top_ent = top_ent.merge(df_ent[["Entidad","Tipo"]].drop_duplicates(), on="Entidad")
            TIPO_COLOR = {"PERSONA":"#E74C3C","ORGANIZACIÓN":"#2980B9","LUGAR":"#27AE60"}
            fig_ner = px.bar(top_ent, x="Menciones", y="Entidad", orientation="h",
                             color="Tipo", color_discrete_map=TIPO_COLOR,
                             template="plotly_white")
            fig_ner.update_layout(height=380, margin=dict(l=0,r=0,t=10,b=0))
            st.plotly_chart(fig_ner, use_container_width=True)

            st.markdown("**Tabla de entidades por noticia:**")
            tabla = df[["titulo","categoria","entidades"]].copy()
            tabla["Personas"] = tabla.entidades.apply(lambda e: ", ".join(e.get("PERSONA",[])))
            tabla["Organizaciones"] = tabla.entidades.apply(lambda e: ", ".join(e.get("ORGANIZACIÓN",[])))
            tabla["Lugares"] = tabla.entidades.apply(lambda e: ", ".join(e.get("LUGAR",[])))
            st.dataframe(tabla[["titulo","categoria","Personas","Organizaciones","Lugares"]].rename(columns={"titulo":"Título","categoria":"Categoría"}),
                         use_container_width=True, height=300)